with stg_imdb_ratings as (

    select imdb_title_id as title_id,
           weighted_average_vote,
           total_votes,
           mean_vote,
           median_vote,
           votes_10,
           votes_9,
           votes_8,
           votes_7,
           votes_6,
           votes_5,
           votes_4,
           votes_3,
           votes_2,
           votes_1,
           allgenders_0age_avg_vote,
           allgenders_0age_votes,
           allgenders_18age_avg_vote,
           allgenders_18age_votes,
           allgenders_30age_avg_vote,
           allgenders_30age_votes,
           allgenders_45age_avg_vote,
           allgenders_45age_votes,
           males_allages_avg_vote,
           males_allages_votes,
           males_0age_avg_vote,
           males_0age_votes,
           males_18age_avg_vote,
           males_18age_votes,
           males_30age_avg_vote,
           males_30age_votes,
           males_45age_avg_vote,
           males_45age_votes,
           females_allages_avg_vote,
           females_allages_votes,
           females_0age_avg_vote,
           females_0age_votes,
           females_18age_avg_vote,
           females_18age_votes,
           females_30age_avg_vote,
           females_30age_votes,
           females_45age_avg_vote,
           females_45age_votes,
           top1000_voters_rating,
           top1000_voters_votes,
           us_voters_rating,
           us_voters_votes,
           non_us_voters_rating,
           non_us_voters_votes
    from {{ source('imdb', 'src_imdb_ratings') }}

)

select *
from stg_imdb_ratings